[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "https://destudio.bigcartel.com"
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "allow-from https://destudio.bigcartel.com/"
X-XSS-Protection = "0" 